### ISSUE TITLE
Missing `cattr_accessor` method when using only librato-metrics

### ISSUE THREAD

**Issue by thibaudgg** [StatusPage/librato-sidekiq#3]
I'm using librato-sidekiq outside of a rails/rack app and activesupport deps is required.

librato-sidekiq should add `activesupport` gem as a dependency and add `require 'active_support/core_ext/class/attribute_accessors'`

In the meantime I added `gem 'activesupport', require: 'active_support/core_ext/class/attribute_accessors'` in my Gemfile.

Thanks for the gem!

**Comment by fphilipe** [comment]
Also hit this. This does not seem to be fixed yet.

Also, I think it's an overkill to include activesupport just for this when you can achieve the same with plain ruby.

**Comment by scootklein** [comment]
can you submit a pull request for this?
